(*========== Lexical Tokens ==========*)


(* Character definition *)
LetterUppercase ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
                  | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
                  | "U" | "V" | "W" | "X" | "Y" | "Z" ;
LetterLowercase ::= "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
                  | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
                  | "u" | "v" | "w" | "x" | "y" | "z" ;
Letters         ::= LetterLowercase | LetterUppercase ;
Digits          ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
Symbols         ::= "+" | "-" | "*" | "/" | "=" | "(" | ")" | "{" | "}" | "["
                  | "]" | "," | ":" | "." | " " ;

(* Miscellaneous *)
Identifier      ::= Letters, { Letters | Digits | "_" } ;

(* Data Types *)
RANGETYPE       ::= { Digits } TO { Digits } ;
DATETYPE        ::= Digits, Digits, "/", Digits, Digits,
                    "/", Digits, Digits, Digits, Digits ;
                    (* Basically DD/MM/YYYY *)
REALTYPE        ::= { Digits }, ".", { Digits } ;
INTEGERTYPE     ::= { Digits } ;
CHARTYPE        ::= "'", ( Letters | Digits | Symbols ), "'" ;
STRINGTYPE      ::= '"', { ( Letters | Digits | Symbols ) }, '"' ;
BOOLEANTYPE     ::= "TRUE" | "FALSE" ;

(* Logical Operators *)
EQUALTO         ::= "==" ;
NOTEQUALTO      ::= "<>" ;
GREATEQUAL      ::= ">=" ;
LESSEQUAL       ::= "<=" ;
GREAT           ::= ">" ;
LESS            ::= "<" ;

(* Arithmetic Operators *)
DIVIDEINTEGER   ::= "DIV" ;

(* Miscellaneous *)
ASSIGN          ::= "<-" ;
COMMENT         ::= "//", { Letters | Digits | Symbols };